(ns com.biffweb.tasks.setup
  (:require [clojure.java.io :as io]
            [clojure.java.shell :as sh]
            [clojure.string :as str]
            [com.biffweb.tasks.generate :as generate]
            [com.biffweb.tasks.install-tailwind :as install-tailwind]
            [com.biffweb.tasks.util :as util]))

(def ^:private template-main-ns "com.example")
(def ^:private pre-commit-hook-path ".git/hooks/pre-commit")
(def ^:private tests-workflow-path ".github/workflows/tests.yml")

(defn- project-root []
  (io/file (System/getProperty "user.dir")))

(def ^:private pre-commit-hook
  "#!/usr/bin/env bash
set -euo pipefail

clj -M:run format

if ! git diff --quiet --exit-code; then
  echo 'Formatting changed tracked files. Review the diff, stage the changes, and commit again.' >&2
  exit 1
fi
")

(def ^:private tests-workflow
  "# This file is autogenerated by biff-tasks setup. Do not edit.
name: tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeLaGuardo/setup-clojure@13.2
        with:
          cli: latest
      - run: clj -M:run test
")

(defn- prompt [msg]
  (print msg)
  (flush)
  (or (not-empty (read-line))
      (recur msg)))

(defn- ns->path [s]
  (-> s
      (str/replace "-" "_")
      (str/replace "." "/")))

(defn- tracked-files []
  (let [{:keys [exit out err]} (sh/sh "git" "ls-files" :dir (.getPath (project-root)))]
    (when-not (zero? exit)
      (throw (ex-info "git ls-files failed" {:exit exit :err err})))
    (->> out
         str/split-lines
         (remove str/blank?))))

(defn- rewrite-main-namespace! [new-main-ns]
  (let [old-path (ns->path template-main-ns)
        new-path (ns->path new-main-ns)
        root     (project-root)
        files    (map (fn [relative-path]
                        [(io/file root relative-path) relative-path])
                      (tracked-files))]
    (doseq [[file relative-path] files]
      (let [dest-path    (str/replace relative-path old-path new-path)
            dest-file    (io/file root dest-path)
            contents     (slurp file)
            new-contents (str/replace contents template-main-ns new-main-ns)]
        (cond
          (not= relative-path dest-path)
          (do
            (io/make-parents dest-file)
            (spit dest-file new-contents)
            (io/delete-file file))

          (not= contents new-contents)
          (spit file new-contents))))
    (doseq [root ["src" "test"]]
      (let [dir (io/file (project-root) root old-path)]
        (loop [dir dir]
          (when (and (.exists dir)
                     (.isDirectory dir)
                     (empty? (seq (.listFiles dir))))
            (io/delete-file dir)
            (when-let [parent (.getParentFile dir)]
              (recur parent))))))))

(defn- needs-main-namespace-setup? []
  (let [configured-main-ns (some-> (util/read-config)
                                   :biff.tasks/main-ns
                                   str)]
    (or (= configured-main-ns template-main-ns)
        (.exists (io/file (project-root) "src" (str (ns->path template-main-ns) ".clj"))))))

(defn- write-generated-file! [relative-path contents]
  (let [file (io/file (project-root) relative-path)]
    (io/make-parents file)
    (spit file contents)
    file))

(defn- install-pre-commit-hook! []
  (let [hook-file (write-generated-file! pre-commit-hook-path pre-commit-hook)]
    (.setExecutable hook-file true)))

(defn- write-tests-workflow! []
  (write-generated-file! tests-workflow-path tests-workflow))

(defn setup
  "Initializes a freshly cloned Biff project."
  [& [main-ns]]
  (when (needs-main-namespace-setup?)
    (let [main-ns (str (or main-ns
                           (prompt "Enter main namespace (e.g. com.example): ")))]
      (rewrite-main-namespace! main-ns)
      (println "Updated the main namespace to" main-ns ".")))
  (generate/ensure-config-files)
  (install-tailwind/ensure-tailwind-installed)
  (install-pre-commit-hook!)
  (write-tests-workflow!))
